---
- hosts: localhost
  tasks:
   - name: Run sleep.sh
     command: /home/ansible/sleep.sh
     async: 60
     poll: 10 


#################################
1. It prevent interruption from ssh timeouts for long running operations.
2. A poll value for how oftern ansible should check back.
3. A poll value of 0 will hava ansible not check back on task.
