

# The data read from the file can then be fed to the Ansible playbook as a variable.
# ref : https://hub.packtpub.com/depth-look-ansible-plugins/
---
- hosts: localhost
  vars:
    data: "{{ lookup('file', './test-file.txt') }}"
  tasks:
    - debug: msg="File contents {{ data }}"
                                        
# read data off a local file, test-file.txt, from the playbook’s root directory into a data variable. This variable is then fed to the task : debug module, which uses the data variable to print it onscreen.                                        
