---
- name: Get-URL Download the Protected File
  hosts: appserver
  tasks:
    - name: Access the WebSite and make sure the URL is live
      uri:
        url: http://mwiweb02/admin/secure.txt
        status_code: 401
      register: validateurl

    - name: "INFO: HTTP Response for the URL"
      debug: var=validateurl.msg

    - name: Access the same URL with Basic Authentication and Download the file
      get_url:
        url: http://mwiweb02/admin/secure.txt
        url_password: Sarav@123
        url_username: sarav
        dest: /tmp/secure.txt

    - name: Display the File contents
      shell: >
         cat /tmp/secure.txt
      register: shellout

    - name: "INFO: Display the File Contents"
      debug: var=shellout.stdout_lines
      
 #https://www.middlewareinventory.com/blog/ansible-get_url-examples-how-to-download-file-from-url/
