---
- hosts: localhost
  vars_files:
    - /root/github/Ansible/vault
  tasks:
    - name: Add secret text to open.txt
      lineinfile:
        path: /home/open.txt
        create: yes
        line: "{{password}}"
      no_log: true  
          

